apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-alerts
  labels:
    role: alert-rules
spec:
  groups:
  - name: myapp.rules
    rules:

    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status="500"}[2m]))
        /
        sum(rate(http_requests_total[2m])) > 0.01
      for: 2m
      labels:
        severity: critical

    - alert: HighLatency
      expr: |
        histogram_quantile(
          0.95,
          sum(rate(http_request_duration_seconds_bucket[2m])) by (le)
        ) > 1
      for: 3m
      labels:
        severity: warning

    - alert: PodCrashLoop
      expr: rate(kube_pod_container_status_restarts_total[5m]) > 3
      labels:
        severity: critical
